############################
#Basic Settings
############################
# hostname to visit your web site
WebHostName = "http://example.com"
# website name to show
WebApplicationName = "MinoIC - PE"
 # website description to show
WebDescription = "Pterodactyl 服务器出售系统"
# website Admin address
WebAdminAddress = "ADMIN <admin@example.com>"

############################
#Pterodactyl Settings
############################
# your pterodactyl panel hostname
PterodactylHostname = "https://pterodactyl.example.com"
# pterodactyl admin token
PterodactylToken = ""

############################
#Database Settings
############################
DatabaseSalt = "PEOSALT"
MYSQLHost = "mysql:3306"
MYSQLUsername = "root"
MYSQLUserPassword = "PEOMYSQLPASSWORD"
MYSQLDatabaseName = "peo"
SqlTablePrefix = "pe_"
RedisHost = "redis:6379"

############################
#SMTP settings
############################
# if set to false, we wont send any email to user
SMTPEnabled = false
SMTPHost = "smtpdm-ap-southeast-1.aliyun.com"
SMTPPort = 80
SMTPSendFrom = "ADMIN <admin@example.com>"
SMTPUsername = "admin@example.com"
SMTPUserPassword = "yourpassword"
 #TLS/SSL
SMTPEncryption = "TLS"
#if DeleteEmailConfirm be set to true all admins will receive an email before Server being deleted
DeleteEmailConfirm = true

############################
#Misc Settings
############################
# check if you want user to recharge balance
RechargeMode = false
# if set to false, we wont accept any discount
TotalDiscount = false
# fill if you want to enable alipay recharge
AliPayEnabled = false
AliPayPublicKey = ""
AliPayPrivateKey = ""
AliPayAppID = ""
# toggle album
AlbumEnabled = false
SocialLink = "https://github.com/minoic/peo"
SocialLinkTitle = "社区"
Language = "zh-CN"